### ISSUE TITLE
找不到Form.cs怎么看空间布局呢

### ISSUE THREAD

**Issue by BeimingCharles** [ZhaoQi99/SNNU_CSharp_Course#1]

**Comment by ZhaoQi99** [comment]
布局应该是在`Form1.Designer.cs`.

**Comment by BeimingCharles** [comment]
收到，祁老师



---- 回复的原邮件 ----
| 发件人 | Qi ***@***.***> |
| 日期 | 2024年07月19日 11:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SNNU-CS/snnu-csharp-course] 找不到Form.cs怎么看空间布局呢 (Issue #1) |

布局应该是在Form1.Designer.cs.
